#!/usr/bin/python
#+
# Test of my crosscode11 PDP-11 code-generation library.
#
# Written by Lawrence D'Olivero <ldo@geek-central.gen.nz>.
#-

import sys
from crosscode11 import \
	CodeBuffer, \
	o, op, \
	dump_simh

c = CodeBuffer()
tto_xcsr = c.label("tto_xcsr", 0177564)
tto_xbuf = c.label("tto_xbuf", 0177566)
thestr = c.label("thestr")

c.psect("main")
c.org(0200)
start = c.label("start", True)
c.refer(thestr, c.dot() + 2, c.LabelClass.b16a)
c.i(op.MOV, 0, o.R0)
loop = c.label("loop", True)
done = c.label("done")
c.i(op.MOVB, o.R0i, o.R1)
c.i(op.BEQ, 0)
c.refer(done, c.dot() - 2, c.LabelClass.w8)
wait = c.label("wait", True)
c.i(op.BIT, 0000200, (o.a, 0))
c.refer(tto_xcsr, c.dot() - 2, c.LabelClass.b16a)
c.i(op.BEQ, 0)
c.refer(wait, c.dot() - 2, c.LabelClass.w8)
c.i(op.MOVB, o.R1, (o.a, 0))
c.refer(tto_xbuf, c.dot() - 2, c.LabelClass.b16a)
c.i(op.BR, 0)
c.refer(loop, c.dot() - 2, c.LabelClass.w8)
done.resolve()
lastwait = c.label("lastwait", True) # wait for last character to be output
c.i(op.BIT, 0000200, (o.a, 0))
c.refer(tto_xcsr, c.dot() - 2, c.LabelClass.b16a)
c.i(op.BEQ, 0)
c.refer(lastwait, c.dot() - 2, c.LabelClass.w8)
c.i(op.HALT)

c.psect("data")
c.org(0300)
thestr.resolve()
for ch in "hi there!\015\012" :
	c.b(ord(ch))
#end for
c.b(0)

c.start(start)
dump_simh(c, sys.stdout)
